upstream myarea_apps_app {
    server web:5000;
    keepalive 16;
}

server {
    listen 80;
    server_name apps.wrds361.com;

    resolver 127.0.0.11 valid=10s;

    location /static/ {
        proxy_pass http://myarea_apps_app;
    }

    location / {
        proxy_pass         http://myarea_apps_app;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
}
